CREATE TABLE Clientes (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    sobrenome  VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);

INSERT INTO Clientes(nome, sobrenome, email) VALUES ('JOÃO','SILVA','JOAO@SILVA.COM');

INSERT INTO Clientes(nome, sobrenome, email) VALUES ('MARIA','SANTOS','MARIA@SANTOS.COM');

INSERT INTO Clientes(nome, sobrenome, email) VALUES ('JOSÉ','MIGUEL','JOSÉ@MIGUEL.COM');

INSERT INTO Clientes(nome, sobrenome, email) VALUES ('ANTÔNIO','SILVA','ANTÔNIO@SILVA.COM');

SELECT * FROM Clientes; 

CREATE TABLE pedidos(
    ID SERIAL PRIMARY KEY,
    ID_CLIENTES INT,
    DATA_PEDIDO DATE,
    TOTAL NUMERIC(6,2),
    STATUS TEXT CHECK(STATUS IN ('EM ANDAMENTO','FINALIZADO','CANCELADO')),
    FOREIGN KEY (ID_CLIENTES) REFERENCES Clientes(id)
);

DROP TABLE pedidos;

ALTER TABLE pedidos ALTER COLUMN STATUS SET DEFAULT 'EM ANDAMENTO';

INSERT INTO pedidos(ID_CLIENTES, DATA_PEDIDO, TOTAL) VALUES 
(1,'2024-04-01',50.00),
(2,'2024-04-02',75.00),
(1,'2024-04-03',120.00),
(3,'2024-04-04',35.00),
(2,'2024-04-05',90.00);

SELECT * FROM pedidos;
